[project]
name = 'clarity-defi-vault'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sip-010]
path = 'contracts/sip-026.clar'
clarity_version = 2
epoch = 2.4

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.sip-026-trait]
path = 'contracts/sip-026-trait.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
